/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Christian
 */

import EDD.*;
import static Interfaces.Main.graph;
import javax.swing.JOptionPane;

public class Add extends javax.swing.JFrame {

    /**
     * Creates new form Add
     */
    public static Main v1;
    
    public Add(Main v1) {
        initComponents();
        this.v1 = v1;
        v1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add_icon = new javax.swing.JLabel();
        city_icon = new javax.swing.JLabel();
        add_vertex = new javax.swing.JButton();
        input_vertex = new javax.swing.JTextField();
        finish = new javax.swing.JButton();
        back = new javax.swing.JButton();
        TITULO_Principal = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número del vértice:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
<<<<<<< Updated upstream

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Arista:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Peso:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));
=======
>>>>>>> Stashed changes

        add_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus.png"))); // NOI18N
        jPanel1.add(add_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 30, 30));

        city_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cities.png"))); // NOI18N
        jPanel1.add(city_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        add_vertex.setForeground(new java.awt.Color(0, 0, 0));
        add_vertex.setText("Añadir vértice");
        add_vertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_vertexActionPerformed(evt);
            }
        });
<<<<<<< Updated upstream
        jPanel1.add(add_vertex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, -1));

        agg_aristaAndPeso.setForeground(new java.awt.Color(0, 0, 0));
        agg_aristaAndPeso.setText("Añadir peso y arista");
        agg_aristaAndPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agg_aristaAndPesoActionPerformed(evt);
            }
        });
        jPanel1.add(agg_aristaAndPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 150, -1));
=======
        jPanel1.add(add_vertex, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 130, -1));
>>>>>>> Stashed changes

        input_vertex.setForeground(new java.awt.Color(0, 0, 0));
        input_vertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_vertexActionPerformed(evt);
            }
        });
<<<<<<< Updated upstream
        jPanel1.add(input_vertex, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 200, 20));

        input_arista.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(input_arista, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 160, -1));

        input_weight.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(input_weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 160, -1));
=======
        jPanel1.add(input_vertex, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 160, -1));
>>>>>>> Stashed changes

        finish.setForeground(new java.awt.Color(0, 0, 0));
        finish.setText("Siguiente");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        jPanel1.add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 80, 40));

        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("Volver");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 80, 40));

        TITULO_Principal.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        TITULO_Principal.setForeground(new java.awt.Color(255, 255, 255));
        TITULO_Principal.setText("Añadir ciudad");
        jPanel1.add(TITULO_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        background.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        background.setText("Gabriel Flores");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void agg_aristaAndPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agg_aristaAndPesoActionPerformed
        int num = Integer.parseInt(input_vertex.getText());
        Vertex vertex2 = new Vertex(num);
        
        if(graph.findCity(vertex2)){
//            Edge edge = new Edge(graph.findCity2(Integer.parseInt(input_vertex.getText())), graph.findCity2(num), weight);
//            graph.findCity2(Integer.parseInt(input_vertex.getText())).getListAdy().addEnd(edge);
            JOptionPane.showMessageDialog(null, "La ciudad ya existe!");
        }else{
            JOptionPane.showMessageDialog(null, "Ciudad agregada con exito!");
            this.setVisible(false);
            Add2 window1 = new Add2(v1);
            window1.setVisible(true);
        }
    }//GEN-LAST:event_agg_aristaAndPesoActionPerformed


    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
            this.setVisible(false);
            Add2 windowadd2 = new Add2(v1);
            windowadd2.setVisible(true);

    }//GEN-LAST:event_finishActionPerformed

    private void add_vertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_vertexActionPerformed
        try {
            int num = Integer.parseInt(input_vertex.getText());
            Vertex vertexAux = new Vertex(num);
            graph.addCity(vertexAux);
            JOptionPane.showMessageDialog(null, "Vértice creado con éxito");
            this.setVisible(false);
            Welcome b = new Welcome();
            Main window1 = new Main(b);
            Add window2 = new Add(window1);
            window2.setVisible(true);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Introduzca un dato válido");
        }
    }//GEN-LAST:event_add_vertexActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        Welcome b = new Welcome();
        Main window1 = new Main(b);
        window1.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void input_vertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_vertexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_vertexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO_Principal;
    private javax.swing.JLabel add_icon;
    private javax.swing.JButton add_vertex;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel city_icon;
    private javax.swing.JButton finish;
    private javax.swing.JTextField input_vertex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
