/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import EDD.Edge;
import EDD.Vertex;
import static Interfaces.Main.graph;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author 58414
 */
public class Add2 extends javax.swing.JFrame {

    /**
     * Creates new form Add2
     */
    public static Add v1;
    DefaultComboBoxModel comboModel1 = new DefaultComboBoxModel();
    DefaultComboBoxModel comboModel2 = new DefaultComboBoxModel();
    
    public Add2(Add v1) {
        initComponents();
        v1.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        for (int i = 0; i < graph.numberCities(); i++) {
            Vertex vertexAux = (Vertex) graph.getCities().getValor(i);
            comboModel1.addElement(vertexAux.getNumCity());
            comboModel2.addElement(vertexAux.getNumCity());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        finalCity = new javax.swing.JComboBox<>();
        initialCity = new javax.swing.JComboBox<>();
        agg_arista = new javax.swing.JButton();
        listo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        inputDistance = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese la distancia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel2.setText("Ciudad Final");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        finalCity.setModel(comboModel2);
        finalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalCityActionPerformed(evt);
            }
        });
        getContentPane().add(finalCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        initialCity.setModel(comboModel1);
        initialCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initialCityActionPerformed(evt);
            }
        });
        getContentPane().add(initialCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        agg_arista.setText("Agregar Arista");
        agg_arista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agg_aristaActionPerformed(evt);
            }
        });
        getContentPane().add(agg_arista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        listo.setText("Listo");
        listo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listoActionPerformed(evt);
            }
        });
        getContentPane().add(listo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel3.setText("Ciudad Inicio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        inputDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDistanceActionPerformed(evt);
            }
        });
        getContentPane().add(inputDistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agg_aristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agg_aristaActionPerformed
        if(!initialCity.getSelectedItem().equals(finalCity.getSelectedItem())){
            int startCity = Integer.parseInt((String) initialCity.getSelectedItem());
            int endtCity = Integer.parseInt((String) finalCity.getSelectedItem());

            Edge edge = new Edge(graph.findCity2(startCity), graph.findCity2(endtCity), Double.parseDouble(inputDistance.getText()));
            JOptionPane.showMessageDialog(null, "Arista cargada con exito!");
            graph.findCity2(startCity).addEdges(edge);
            
        }
    }//GEN-LAST:event_agg_aristaActionPerformed

    private void listoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listoActionPerformed
        this.setVisible(false);
        Welcome b = new Welcome();
        Main window1 = new Main(b);
        window1.setVisible(true);
    }//GEN-LAST:event_listoActionPerformed

    private void finalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_finalCityActionPerformed

    private void initialCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialCityActionPerformed

    private void inputDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDistanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add2(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agg_arista;
    private javax.swing.JComboBox<String> finalCity;
    private javax.swing.JComboBox<String> initialCity;
    private javax.swing.JTextField inputDistance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton listo;
    // End of variables declaration//GEN-END:variables
}
